#!/usr/bin/env bash
#displays informaion about subdomains on specific domains
Information="$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
IP=$(echo "$Information" | awk '{print $5}')
TYPE=$(echo "$Information" | awk '{print $4}')
echo "The subdomain ${2} is a ${TYPE} record and points to ${IP}"
