#!/usr/bin/env bash
# Install the load balanecer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo  add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*

echo 'ENABLED=1' >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg haproxy.cfg.org
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend ThePaapyK_front
	bind *:80
	mode http
	default_backend ThePaapyK_back
backend ThePaapyK_back
    balance roundrobin
    server 3158-web-01 3.94.185.28 check
    server 3158-web-02 35.153.17.98 check
CONFIG
sudo service haproxy restart
