#!/usr/bin/env bash
# shellcheck disable=SC2034
# quart et huit

n="Best School"
i="1"
while [ "$i" -le "10" ];
do
if [ "$i" = "4" ]
then
echo "bad luck"
elif [ "$i" = "8" ]
then
echo "good luck"
else
echo "$n"
fi
(( i++ ))
done
