#!/usr/bin/env bash
# shellcheck disable=SC2034
#nested loop

i="0"
while [ "$i" -le "12" ];
do
	echo "Hour: $i"
	j="1"
	while [ "$j" -le "59" ] && [ $i -lt "12" ];
	do
		echo "$j"
		(( j++ ))
	done
	(( i++ ))
done
